language: node_js
node_js:
  - "8"
  - "7"
  - "6"
install:
  # Output imagemagick version
  - convert -version
  # Install dependencies
  - yarn
before_install:
  - sudo apt-get install graphicsmagick -y
script:
  - yarn lint
  - yarn test:unit
  - yarn test:benchmark
